    o
Blog
Comunidad
okteto.com (1.3)
Conseguir prueba gratuita
Bienvenidos
Entornos de desarrollo
Descripci+APM-n general
Okteto CLI
Desplegando
Desde repositorios Git
Desde repositorios privados
De los gr+AOE-ficos de Helm
Secretos de Okteto
Exponiendo su aplicaci+APM-n
Servicio de compilaci+APM-n
Registro de Contenedores
Instant+AOE-neas de volumen
Espacios de nombres
Credenciales de Kubernetes
Fichas de acceso personal
Sincronizaci+APM-n de archivos
Servidor SSH
Entornos de vista previa
Administraci+APM-n
Okteto autohospedado
Referencias
Okteto CLI
Manifiesto Okteto
Migraci+APM-n a Okteto CLI 2.0
Componer ventana acoplable
preguntas frecuentes
Permisos de GitHub
Problemas conocidos
Tutoriales
Muestras
Versi+APM-n: okteto.com (1.3)
Referencia de redacci+APM-n de Docker
Docker Compose es para desarrolladores que no quieren lidiar con las complejidades de los manifiestos de Kubernetes. Okteto implementa y ampl+AO0-a la especificaci+APM-n Compose para facilitar el desarrollo de aplicaciones Docker Compose en Kubernetes.

services:
  vote:
    build: vote
    scale: 2
    environment:
      - FLASK_ENV=development
    command: python app.py
    ports:
      - 8080:8080
    volumes:
      - ./vote:/src

  redis:
    image: redis
    ports:
      - 6379
    volumes:
      - redis:/data

volumes:
  redis:
